### ISSUE TITLE
Restoring Exported Settings - Curly Braces

### ISSUE THREAD

**Issue by djg31337** [4chan/4chan-JS#121]
The address bar in Firefox decodes the percent-encoded curly braces generated by the export settings button. It appears this is causing an issue when using the link to restore exported settings.

Unsure if this is the root cause or would help, but in `initFromURL` `frag` is set to `window.location.hash`. It may be better to use `window.location.hash.split("#").splice(1).join("#")` per the comment on this SO answer: https://stackoverflow.com/a/4835922.

**Comment by desuwa** [comment]
Seems to be working fine in Firefox 74.

Try using a blank tab when restoring settings (opennew  tab -> click bookmarklet / paste link in url bar)

**Comment by djg31337** [comment]
Didn't work unfortunately. Running FF 74 64-bit on Debian. Tried FF Safe Mode, no luck. For reference, screenshots attached of bookmark, c/p into address bar, and result after hitting enter in address bar.
![Screenshot from 2020-03-27 13-46-38](https://user-images.githubusercontent.com/5186366/77784902-b6c08480-7031-11ea-9c7b-577e1664e39a.png)
![Screenshot from 2020-03-27 13-47-34](https://user-images.githubusercontent.com/5186366/77784906-b922de80-7031-11ea-8313-c504dca824f1.png)
![Screenshot from 2020-03-27 13-47-43](https://user-images.githubusercontent.com/5186366/77784910-baeca200-7031-11ea-9157-0ad699cb3764.png)

**Comment by desuwa** [comment]
Try in a private window. The settings from the URL from won't overwrite existing settings.
If it works in private mode you can clear your Local Storage through the dev console (F12 > *Storage* on top > *Local Storage* on the left > right click on *https*://boards.4chan.... > Delete All). Make sure you are clearing settings on the destination domain (https).

**Comment by djg31337** [comment]
Private window worked. Clearing the local storage worked. Thank you. Closing the issue.
