### ISSUE TITLE
Saving Pictures With the uploaded Filename

### ISSUE THREAD

**Issue by leveechan** [4chan/4chan-JS#41]
Is there anyway to enable that, cause my pic folder is just a swath of meaningless numbers. I know 4chanPlus had that for a while, but since this extension is on the site itself I thought it might be possible. Hell I'd be fine with 1350273866784-(original filename).

**Comment by darkred** [comment]
[**@qqueue**](https://github.com/qqueue) commented on [Oct 30, 2012, 8:00 AM GMT+2](https://github.com/4chan/4chan-JS/issues/41#issuecomment-9895785 "2012-10-30T06:00:25Z - Replied by Github Comment Enhancer"):
> This is likely dependent on the `download` attribute, which is only implemented in Chrome at the moment: [https://bugzilla.mozilla.org/show_bug.cgi?id=676619](https://bugzilla.mozilla.org/show_bug.cgi?id=676619) 

That bug has been fixed.
So, maybe @desuwa, you could reconsider adding this feature.

**Comment by ccd0** [comment]
@darkred
The problem is that the download attribute doesn't work for cross-origin links.  But this could be worked around by using a link in an iframe on i.4cdn.org.

**Comment by Fixer-007** [comment]
Still relevant in 2019

**Comment by cosmon560** [comment]
Still relevant in 2021
