### ISSUE TITLE
Can't unhide threads on the catalog

### ISSUE THREAD

**Issue by Hupotronic** [4chan/4chan-JS#74]
Right now you can hide threads on the catalog with a shift+click. You can also view hidden threads separately. However, you can't unhide any hidden threads in any manner.

Seeing as how shift+clicking a thread in the hidden thread view "double-hides" a thread temporarily, I guess you could just change shift+click to unhide a thread in the hidden view, just like how it hides a thread in the regular view.

**Comment by g-gundam** [comment]
@CharaArc This is fixed now.  Shift-Click to unhide works.  You can also unhide a thread through its thread-specific menu.

![Screenshot from 2021-06-01 10-08-16](https://user-images.githubusercontent.com/9591914/120364066-a5bc7480-c2c1-11eb-81f1-5896ec6dd984.png)
